### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SephpaCreditTransfer' not found

### ISSUE THREAD

**Issue by xaviItailored** [AbcAeffchen/Sephpa#20] opened 2019-05-31 17:11 UTC
Hello.
I have all the depencies but this error generates me.

I checked all the routes and all is correct.

Does anyone know where the error may come from?

**Comment by AbcAeffchen** [comment] 2020-04-18 21:10
Hello,

Sorry, somehow I missed this one and just found it, because I try to resolve all issues before the new release. 

It sounds like an issue with a invalid link to the autoloader due to the lack of a good documentation. But since this is almost a year old I think it it either fixed or not reproducible anymore. So I close this.

A better documentation is on its way.

**Closed by AbcAeffchen** 2020-04-18 21:10 UTC
